# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworksServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, choices=[('SECUNDARIO', 'Secundário'), ('LICENCIATURA', 'Licenciatura'), ('MESTRADO', 'Mestrado'), ('DOUTORAMENTO', 'Doutoramento')], max_length=100),
        ),
    ]
