# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dotworksServer', '0003_internship_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='application_deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 17, 16, 40, 46, 448538, tzinfo=utc), verbose_name='aplications deadline'),
            preserve_default=False,
        ),
    ]
