# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotworksServer', '0004_internship_application_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='name',
            new_name='title',
        ),
    ]
