# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotworksServer', '0006_auto_20160329_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotworksServer.Internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotworksServer.Student')),
            ],
        ),
    ]
