# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworksServer', '0007_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='category',
            field=models.CharField(choices=[('CUR', 'Curricular'), ('PRO', 'Profissional'), ('VER', 'Verao')], default='CUR', max_length=20),
            preserve_default=False,
        ),
    ]
