# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0003_remove_student_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='payment',
            field=models.CharField(choices=[('R', 'Remunerado'), ('NR', ' Não Remunerado')], max_length=30),
        ),
    ]
