# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0005_auto_20170309_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='avatar',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
