# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-11 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0006_internship_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='degree',
            new_name='curso',
        ),
    ]
