# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-11 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0007_auto_20170311_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='curso',
            new_name='degree',
        ),
    ]
