# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0008_auto_20170311_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
