# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-12 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0010_auto_20170312_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='beginning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Beginning date'),
        ),
    ]
