# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-12 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0011_auto_20170312_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 mês'), (2, '2 meses'), (3, '3 meses'), (4, '4 meses'), (5, '5 meses'), (6, '6 meses'), (7, '7 meses'), (8, '8 meses'), (9, '9 meses'), (10, '10 meses'), (11, '11 meses'), (12, '12 meses')], null=True),
        ),
    ]
