# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-13 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0012_auto_20170312_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
