# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-15 22:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0013_auto_20170313_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), size=2),
        ),
    ]
