# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-18 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='facebook',
            new_name='behance',
        ),
    ]
