# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-18 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0002_auto_20170218_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
    ]
