# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-09 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0004_auto_20170309_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(max_length=100),
        ),
    ]
