# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0008_internship_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='beggining_date',
            new_name='beginning_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='linkedin',
            new_name='linkedin',
        ),
    ]
