# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0011_auto_20161018_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='beginning_date',
            field=models.DateField(verbose_name='Beginning date'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='n_positions',
            field=models.IntegerField(),
        ),
    ]
