# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0016_internship_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='answers',
        ),
    ]
