# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 14:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0018_inscription_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=2),
        ),
    ]
