# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotworks_server', '0019_auto_20161025_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='questions',
        ),
    ]
